#开发环境
server:
  port: 8080
  servlet:
    context-path: /jingdong
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat_shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  freemarker:
    request-context-attribute: req #访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false  #缓存
    template-loader-path: classpath:/templates/  #模板加载路径
    charset: utf-8
    settings:
      number_format: '0.##' #数字格式化 无小数点
  #更改路径匹配为 ANT_PATH_MATCHER 否则swagger无法启动
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
swagger:
  enable: true

#设置微信配置
wechat:
  #公众号识别id
#  mpAppId: wx32b98899abc39751
  mpAppId: wx680e2c1d87e8226c
  #公众号秘钥
#  mpAppSecret: da9b44f3ecf3b7b9b76626fd0c4bc928
  mpAppSecret: 913842a25888610d49be5e0a3abd91db
  #微信授权 获取code后 跳转获取用户信息的回调接口
  mpUserInfoUrl: http://qiaomai.natapp4.cc/jingdong/wechat/userInfo
  #微信支付生成的直连商户号
  mchId: 1572824121
  #支付商户秘钥
  mchKey: c56d0e9a7ccec67b4ea131655038d604
  #微信支付证书存储路径
  keyPath: D:/wxpay/WXCertUtil/cert/apiclient_cert.p12
  #微信支付结果异步通知接口
  notifyUrl: http://qiaomai.natapp4.cc/jingdong/pay/notify

#设置开放平台 用于扫码登录
  #微信开放平台唯一应用标识
  openAppId: wx0626ceb11755f952
  #开放平台应用秘钥
  openAppSecret: 2f57579f353115061444ac4599e20d18
  #扫码登录获取信息的回调接口
  openUserInfoUrl: http://qiaomai.natapp4.cc/jingdong/wechat/qrUserInfo
  #根目录
  baseUrl: http://127.0.0.1:8080
